
CREATE TABLE IF NOT EXISTS users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  pronouns VARCHAR(50) NOT NULL DEFAULT '',
  img_url VARCHAR(255) NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  availability_matrix_id UUID NOT NULL REFERENCES user_availability_matrix(id) -- Representing boolean[][] might require a different approach
);

-- CREATE TABLE IF NOT EXISTS users (
--   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   pronouns VARCHAR(50) DEFAULT NULL,
--   sex VARCHAR(50) DEFAULT NULL,
--   age INTEGER DEFAULT NULL,
--   img_urls JSON NOT NULL DEFAULT '[]',
--   bio TEXT NOT NULL DEFAULT '',
--   email VARCHAR(255) NOT NULL,
--   pass_hash VARCHAR(255) NOT NULL,
--   verified BOOLEAN NOT NULL DEFAULT FALSE,
--   availability_matrix_id UUID NOT NULL REFERENCES user_availability_matrix(id)
-- );

CREATE TABLE IF NOT EXISTS user_availability_matrix (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id),
  0_0 BOOLEAN NOT NULL DEFAULT FALSE,
  0_1 BOOLEAN NOT NULL DEFAULT FALSE,
  0_2 BOOLEAN NOT NULL DEFAULT FALSE,
  1_0 BOOLEAN NOT NULL DEFAULT FALSE,
  1_1 BOOLEAN NOT NULL DEFAULT FALSE,
  1_2 BOOLEAN NOT NULL DEFAULT FALSE,
  2_0 BOOLEAN NOT NULL DEFAULT FALSE,
  2_1 BOOLEAN NOT NULL DEFAULT FALSE,
  2_2 BOOLEAN NOT NULL DEFAULT FALSE,
  3_0 BOOLEAN NOT NULL DEFAULT FALSE,
  3_1 BOOLEAN NOT NULL DEFAULT FALSE,
  3_2 BOOLEAN NOT NULL DEFAULT FALSE,
  4_0 BOOLEAN NOT NULL DEFAULT FALSE,
  4_1 BOOLEAN NOT NULL DEFAULT FALSE,
  4_2 BOOLEAN NOT NULL DEFAULT FALSE,
  5_0 BOOLEAN NOT NULL DEFAULT FALSE,
  5_1 BOOLEAN NOT NULL DEFAULT FALSE,
  5_2 BOOLEAN NOT NULL DEFAULT FALSE,
  6_0 BOOLEAN NOT NULL DEFAULT FALSE,
  6_1 BOOLEAN NOT NULL DEFAULT FALSE,
  6_2 BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS courts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  img_url VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL,
  lat FLOAT NOT NULL,
  lng FLOAT NOT NULL,
  is_outdoors BOOLEAN NOT NULL DEFAULT TRUE,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_approved BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS sports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  img_url VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS sports_skill_levels (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sport_id UUID NOT NULL REFERENCES sports(id),
  skill_level SMALLINT NOT NULL,
  skill_name VARCHAR(255) NOT NULL,
  alt_names JSON NOT NULL DEFAULT '[]',
  description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS user_sports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id),
  sport_id UUID NOT NULL REFERENCES sports(id),
  skill_level_id UUID NOT NULL REFERENCES sports_skill_levels(id),
);

CREATE TABLE IF NOT EXISTS user_courts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id),
  court_id UUID NOT NULL REFERENCES courts(id),
);

CREATE TABLE IF NOT EXISTS user_connections (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id UUID NOT NULL REFERENCES users(id),
  user_id UUID NOT NULL REFERENCES users(id),
  is_approved BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id UUID NOT NULL REFERENCES users(id),
  receiver_id UUID NOT NULL REFERENCES users(id),
  dt TIMESTAMP NOT NULL DEFAULT NOW(),
  content TEXT NOT NULL DEFAULT '',
  is_read BOOLEAN NOT NULL DEFAULT FALSE
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE IF NOT EXISTS user_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reporter_id UUID NOT NULL REFERENCES users(id),
  user_id UUID NOT NULL REFERENCES users(id),
  dt TIMESTAMP NOT NULL DEFAULT NOW(),
  reason TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS court_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reporter_id UUID NOT NULL REFERENCES users(id),
  court_id UUID NOT NULL REFERENCES courts(id),
  dt TIMESTAMP NOT NULL DEFAULT NOW(),
  reason TEXT NOT NULL DEFAULT ''
);
